target("test")
    set_group("test")
    set_default(false)
    set_kind("binary")
    add_files("test.cc")
    add_deps("oo")
target_end()

target("vec")
    set_group("test")
    set_default(false)
    set_kind("binary")
    add_files("vec.c", "vec.cc")
    add_deps("oo")
target_end()

target("que")
    set_group("test")
    set_default(false)
    set_kind("binary")
    add_files("que.c", "que.cc")
    add_deps("oo")
target_end()

target("vector")
    set_group("test")
    set_default(false)
    set_kind("binary")
    add_files("vector.c", "vector.cc")
    add_deps("oo")
target_end()
